name: sumajflow_movil
description: "Aplicación móvil de trazabilidad minera – SumajFlow"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI base
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0

  # State management / DI
  get: ^4.6.6

  # Routing
  go_router: ^14.2.0

  # HTTP & API
  http: ^1.2.1
  dio: ^5.7.0

  # Image & Files
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

  # Local Storage
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4

  # Utils / Intl
  intl: ^0.19.0

  # QR / Scanner
  mobile_scanner: ^5.2.3

  # Pin / OTP
  pin_code_fields: ^8.0.1

  # Maps & Geo
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  flutter_map_tile_caching: ^10.1.1

  # Connectivity
  connectivity_plus: ^7.0.0

  # External links
  url_launcher: ^6.3.2

  # WebSocket / Realtime
  stomp_dart_client: ^2.0.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
