name: sumajflow_movil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6

  # Routing
  go_router: ^14.0.0

  # HTTP & API
  http: ^1.2.0
  dio: ^5.4.0

  # Image & Files
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  
  # Storage
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.19.0

  # QR Mobile
  mobile_scanner: ^5.2.3

  # Pin code Fields
  pin_code_fields: ^8.0.1

  flutter_map: ^6.1.0

  latlong2: ^0.9.1

  geolocator: ^14.0.2

  connectivity_plus: ^7.0.0

  url_launcher: ^6.3.2

  stomp_dart_client: ^2.0.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true